Convert a 1D array to a 2D array with 2 rows

Input:

np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

#> array([[0, 1, 2, 3, 4],

#> [5, 6, 7, 8, 9]])

In [5]:
import numpy as np
array = np.arange(10)
array.reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Replace all odd numbers in arr with -1 without changing arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Output:

#> array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

arr

#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array = arr.copy()
array[array % 2 != 0] = -1
array, arr




(array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [6]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_copy = arr.copy()
cond = lambda x: x%2 != 0
 
# new_arr = np.where(arr_copy % 2 != 0, -1, arr_copy)
arr_copy[cond(arr)]= -1
arr_copy


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Get the common items between a and b

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])


Desired Output:

array([2, 4])

In [15]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#manuel:
gemeinsam = set()
for i in range(len(a)):
    for x in range(len(b)):
       if a[i]==b[x]:
        gemeinsam.add(a[i])
gemeinsam_array = np.array(sorted(gemeinsam))
gemeinsam_array
#Desired Output:
#array([2, 4])
#mit numpy
np.intersect1d(a,b)

array([2, 4])

Stack arrays a and b vertically (concatenate recherchieren)

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

#> array([[0, 1, 2, 3, 4],

#> [5, 6, 7, 8, 9],

#> [1, 1, 1, 1, 1],

#> [1, 1, 1, 1, 1]])

In [30]:
#code
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a, b))

#Desired Output:
#> array([[0, 1, 2, 3, 4],
#> [5, 6, 7, 8, 9],
#> [1, 1, 1, 1, 1],
#> [1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Stack the arrays a and b horizontally.

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],

#> [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [29]:
#code
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack((a, b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])