**Aufgabe 0**

Gegeben ist folgender Array:
np.array( ["Rot", "Grün", "Rot", "Blau", "Rot", "Grün", "rot"])
Ermitteln sie die einzigartigen Werte des Arrays mit einer dafür geeigneten numpy
Funktion.

In [3]:
import numpy as np
arr = np.array(["Rot", "Grün", "Rot", "Blau", "Rot", "Grün", "rot"])
arr
unique_values = np.unique(arr)
print(f'Einzigartige Werte: {unique_values}')

Einzigartige Werte: ['Blau' 'Grün' 'Rot' 'rot']


**Aufgabe 0.5** 

Gegeben sind folgende Arrays:

array_a = np.array([1, 2, 3, 4, 5])

array_b = np.array([3, 4, 5, 6, 7])

Ermitteln Sie mit np.isin() welche Werte von array_a in array_b vorhanden sind.

Benutzen Sie einen boolschen Index um einen Array zu erzeugen der die gemeinsamen
Werte enthält.

In [5]:
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([3, 4, 5, 6, 7])
print(np.isin(array_a, array_b))

[False False  True  True  True]


**Aufgabe 0.75**

Führen Sie die folgenden Mengenoperationen an den Arrays aus 0.5 durch:<br>
1. Schnittmenge
2. Vereinigungsmenge
3. Differenzmenge

In [9]:
schnittmenge = np.intersect1d(array_a, array_b)
print(f'Schnittmenge: {schnittmenge}')

print(f'Vereinigungsmenge: {np.union1d(array_a, array_b)}')

print(f'Differenzmenge: {np.setdiff1d(array_a, array_b)}')



Schnittmenge: [3 4 5]
Vereinigungsmenge: [1 2 3 4 5 6 7]
Differenzmenge: [1 2]


**Aufgabe 1**<bp>

Erstellen Sie ein 2D-Array mit zufälligen Werten und sortieren Sie es einmal nach Zeilen
und einmal nach Spalten.<bp>
 Verwenden Sie dafür np.sort() mit Angabe des
entsprechenden Werts für axis .

In [21]:
import numpy as np
import random
arr = np.random.randint(1, 10, size =(5,5))# oder random.random für float
print(f'Original:\n {arr}')

arr_sort_zeihlen= np.sort(arr, axis=1)
print("\nSortiertes Array nach Zeilen:\n", arr_sort_zeihlen)

arr_sort_spalten = np.sort(arr, axis=0)
print("\nSortiertes Array nach Spalten:\n", arr_sort_spalten)



Original:
 [[5 4 2 7 9]
 [9 4 9 3 7]
 [9 1 7 4 5]
 [6 1 2 1 8]
 [5 1 8 3 1]]

Sortiertes Array nach Zeilen:
 [[2 4 5 7 9]
 [3 4 7 9 9]
 [1 4 5 7 9]
 [1 1 2 6 8]
 [1 1 3 5 8]]

Sortiertes Array nach Spalten:
 [[5 1 2 1 1]
 [5 1 2 3 5]
 [6 1 7 3 7]
 [9 4 8 4 8]
 [9 4 9 7 9]]


**Aufgabe 2**

Gegeben ist folgender Array:

np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

Benutzen Sie  mit dem Argument axis um
die Summe aller Werte für jede Zeile des Arrays zu berechnen.
Das Ergebnis sollte ein 1D-Array sein, das die Summen der jeweiligen Zeilen
enthält.
die Summe aller Werte für jede Spalte des Arrays zu berechnen.
Das Ergebnis sollte ebenfalls ein 1D-Array sein, das die Summen der jeweiligen
Spalten enthält.


In [36]:
array = np.arange(1,13).reshape(3,4)
print(array)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
sum_z = np.sum(arr, axis=1)
sum_s = np.sum(arr, axis=0)
print(f'Summe der Zeihlen: {sum_z}')
print(f'Summe der Spalten: {sum_s}')
# Ausgabe der Form (Shape) des Arrays
print(array.shape)
# array.shape gibt die Dimensionen des Arrays zurück, z.B. (Anzahl der Zeilen, Anzahl der Spalten) bei 2D-Arrays

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Summe der Zeihlen: [10 26 42]
Summe der Spalten: [15 18 21 24]
(3, 4)


In [38]:
# Berechnung der Summe aller Elemente im Array
# np.sum(array) summiert alle Werte im Array unabhängig von der Dimension
# Bei einem 1D-Array wird die Summe aller Elemente berechnet
# Bei einem 2D-Array wird die Summe aller Zeilen und Spalten zusammen berechnet
np.sum(array)

np.int64(78)

Aufgabe 3
Gegeben ist ein 1D-Array mit Integer-Zahlen, der einige Nullen enthält.
np.array([10, 0, 5, 20, 0, 25])
Verwenden Sie np.where() , um ein neues Array zu erstellen, in dem die Werte von 100
durch die Elemente des ursprünglichen Arrays geteilt werden. Wenn ein Element des
Arrays den Wert 0 hat, soll an dieser Stelle np.nan (Not a Number) eingetragen werden.

In [28]:
arr = np.array([10, 0, 5, 20, 0, 25])
result = np.where(arr != 0,  100 / arr, np.nan)
print("Neues Array:", result)

Neues Array: [10. nan 20.  5. nan  4.]


C:\Users\NataliaArchipenko\AppData\Local\Temp\ipykernel_5800\148597496.py:2: RuntimeWarning: divide by zero encountered in divide
  result = np.where(arr != 0,  100 / arr, np.nan)


3.1: Erstellung des Filters
Erstellen Sie einen Filter (in diesem Fall einen booleschen Index), der angibt, welche
Elemente im ursprünglichen Array ungleich 0 sind.

In [30]:
filter_ungleich_null = arr != 0
print("Ursprüngliches Array:", arr)
print(" Filter (ungleich 0):", filter_ungleich_null)

Ursprüngliches Array: [10  0  5 20  0 25]
 Filter (ungleich 0): [ True False  True  True False  True]


3.2: Erstellung des Ergebnis-Arrays
Verwenden Sie den erstellten Filter, um ein neues Array zu erstellen, in dem die Werte
von 100 durch die Elemente des ursprünglichen Arrays geteilt werden. An den Stellen,
an denen der Filter False ist (also die Elemente 0), sollte np.nan eingetragen werden.

In [31]:
ergebnis_array = np.where(filter_ungleich_null, 100 / arr, np.nan)
print("Ergebnis-Array:", ergebnis_array)


Ergebnis-Array: [10. nan 20.  5. nan  4.]


C:\Users\NataliaArchipenko\AppData\Local\Temp\ipykernel_5800\1601001904.py:1: RuntimeWarning: divide by zero encountered in divide
  ergebnis_array = np.where(filter_ungleich_null, 100 / arr, np.nan)


3.3 np.any() und np.all()
Benutzen sie eine der beiden Funktionen um zu testen ob im erstellten Array
mindestens ein np.nan eingetragen ist. Benutzen Sie eine der Funktionen um zu testen
ob im Array kein np.nan vorkommt.

In [32]:
mindestens_ein_nan = np.any(np.isnan(ergebnis_array))
print("Test_nan?", mindestens_ein_nan)


Test_nan? True


3.4: np.nan zählen
Ermitteln sie die Anzahl der np.nan im Ergebnis. Sie können dazu die Funktion sum()
in Verbindung mit dem boolschen Index benutzen.

In [33]:
anzahl_nan = np.sum(np.isnan(ergebnis_array))
print("Anzahl der np.nan im Ergebnis-Array:", anzahl_nan)

Anzahl der np.nan im Ergebnis-Array: 2
