# NumPy Übung - Aufgabe

Jetzt wo wir schon einiges über NumPy gelernt haben können wir unser Wissen überprüfen. Wir starten dazu mit einigen einfachen Aufgaben und steigern uns zu komplizierteren Fragestellungen.

**Importiere NumPy als np**

In [11]:
import numpy as np

**Erstelle ein Array von 10 Nullen**

In [30]:
arr_null =  np.zeros(10)
print(arr_null)

array_of_zeros =  np.array([0.] * 10)
print(array_of_zeros)

ar_null = np.zeros(10)
ar_null


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Erstelle ein Array von 10 Einsen**

In [28]:
arr_ones =  np.ones(10)
arr_ones




array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Erstelle ein Array von 10 Fünfen**

In [31]:
array_fuenf = np.array([5.0] * 10)
array_fuenf

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Erstelle ein Array der Zahlen von 10 bis 50**

In [32]:
arr_10_50 = [[i for i in range(10,51)]]
ar_10_50 = np.array(arr_10_50)
ar_10_50

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

**Erstelle ein Array aller gerader Zahlen zwischen 10 und 50**

In [34]:
arr_10_50_g = [[i for i in range(10,51,2)]]
ar_10_50_g = np.array(arr_10_50_g)
ar_10_50_g

array([[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40,
        42, 44, 46, 48, 50]])

**Erstelle eine 3x3 Matrix, die die Zahlen von 0 bis 8 beinhaltet**

In [36]:
arr_0_8 = np.arange(9)
print(arr_0_8.reshape((3, 3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Erstelle eine 3x3 Einheitsmatrix**

In [37]:
arr_eye = np.eye(3)
arr_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Nutze NumPy, um eine Zufallszahl zwischen 0 und 1 zu erstellen**

In [40]:
random_number = np.random.rand()
print(random_number)

0.3232446766866266


**Nutze NumPy, um ein Array von 25 Zufallszahlen zu erstellen**

In [42]:
data = np.random.randn(25)
data

array([-1.19974967e+00,  3.34947579e-01, -5.15856157e-01, -3.97818249e-01,
       -4.35502214e-01, -1.95635079e-02,  7.63142075e-01, -5.98268361e-01,
       -1.64293223e-01, -1.63806895e-02, -1.06183135e+00, -1.73141869e+00,
        2.95277744e+00, -1.65937049e-01,  1.69842506e-01,  5.93267572e-01,
        8.67257594e-01, -5.78481445e-01,  2.11422131e+00,  7.18467728e-01,
        2.00815450e+00,  6.18100355e-01, -5.15032865e-01,  7.00201632e-01,
       -9.57297205e-04])

**Erstelle die folgende Matrix:**
```py
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

In [47]:
werte = np.linspace(0.01, 1.0, 100)
matrix = werte.reshape((10, 10))
matrix


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**Erstelle ein Array aus 20 gleichmäßig verteilten Punkten zwischen 0 und 1**

In [49]:
arr_ls = np.linspace(0,1, num = 20, endpoint = True)
print(arr_ls)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## NumPy Indexing und Selection

Erzeuge folgende Matrix M:
```py
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [59]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
arr_1_25 = np.array([[i for i in range(1,26)]])
arrey_1_25 = arr_1_25.reshape((5, 5))
print(arrey_1_25)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Benutze Slicing um aus M folgende Matrix auszuwählen:
```py
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

In [64]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
teil = arrey_1_25[2:, 1:]
teil

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Wähle aus M folgenden Wert aus: 20

In [62]:
print(arrey_1_25[3, -1]) 


20


Benutze Slicing um aus M folgende Matrix auszuwählen:
```py
array([[ 2],
       [ 7],
       [12]])
```

In [67]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
t1= arrey_1_25[:3, 1].reshape((3, 1))
t1

array([[ 2],
       [ 7],
       [12]])

Benutze Slicing um aus M folgende Matrix auszuwählen:
```py 
array([21, 22, 23, 24, 25])
````

In [72]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
l=arrey_1_25[-1, :]
l

array([21, 22, 23, 24, 25])

Benutze Slicing um aus M folgende Matrix auszuwählen:
```py
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [71]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
l2= arrey_1_25[3:, :]
l2

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])