## Grundrechenarten
Importieren sie die Bibliothek `numpy` unter dem Namen `np`

In [55]:
import numpy as np

### Eindimensional
Gegeben sind zwei Arrays

In [56]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([5, 6, 7])

Bilden Sie die Summe, Differenz und das Produkt

In [57]:
sum = arr1 + arr2
dif = arr1 - arr2
mul= arr1 * arr2 #Produkt
print(f' Summe : {sum}')
print(f' Differenz: {dif}')
print(f' Produkt: {mul}')

 Summe : [ 6  8 10]
 Differenz: [-4 -4 -4]
 Produkt: [ 5 12 21]


Was passiert, wenn Sie statt arr2, eine einzelne Zahl (num = 5) benutzen?

In [58]:
sum_mit_zahl = arr1 + 5 # zu jedem Element des Arreys wird 5 addiert, arr1 = [1 2 3]
print(sum_mit_zahl) # [6 7 8]

[6 7 8]


### Zweidimensional
Diesmal ist eine Matrix gegeben:

In [59]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

Was passiert, wenn eine einzelne Zahl (num = 5) addieren?

In [60]:

num = 5 
sum_2d_und_zahl = arr_2d + num
print(sum_2d_und_zahl)# zu jedem Element des Arrays wird 5 addiert

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


Wie muss der Array aussehen, den man auf arr_2d addiert, damit das Ergebnis
```py
array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])
```       
ist? 


In [63]:
array_new= [[1],[2],[3]]

sum_2_Arrays = arr_2d + array_new
sum_2_Arrays

# andere Variante:
#print(arr_2d+[[1],[2],[3]])

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

Reshape
Oft ist es hilfreich, die Elemente eines Arrays anders anzuordnen. So kann man z.B. aus einem eindimensionalen Array der Länge 15, einen zweidimensionalen Array mit der Shape (3, 5) machen (drei Zeilen, fünf Spalten).

In [66]:
arr_1d = np.arange(15)
arr_2d = arr_1d.reshape((3, 5))

Machen Sie aus arr_2d einen Array mit

- fünf Zeilen und drei Spalten!

- fünfzehn Zeilen und einer Spalte

- einer Zeile und fünfzehn Spalten

- einen eindimensionalen Array

In [72]:
print('Fünf Zeilen und drei Spalten :\n' , arr_2d.reshape(5,3), end = '\n\n')

arr_2d_15z_1s = arr_2d.reshape((15,1))
print(f' Fünfzehn Zeilen und eine Spalte:\n {arr_2d_15z_1s}\n\n')

arr_2d_1z_15s = arr_2d.reshape((1,15))
print(f'Eine Zeile und fünfzehn Spalten:\n {arr_2d_1z_15s}\n\n')

arr_2d_eindim= np.arange(15)
print(arr_2d_eindim) # habe ich das richtig verstanden?



Fünf Zeilen und drei Spalten :
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

 Fünfzehn Zeilen und eine Spalte:
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]


Eine Zeile und fünfzehn Spalten:
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Slicing
### Eindimensional
Gegeben ist ein Array aus zwanzig Elementen:

In [26]:
arr = np.array(list("abcdefghiklmnopqrstuvwxyz"))

Lassen Sie sich die ersten 10 ausgeben (Die Syntax fürs Slicen ist wie bei Python-Listen)

In [27]:
arr[:10]

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k'], dtype='<U1')

### Zweidimensional
Diesmal ist ein zweidimensionaler Array mit vier Zeilen und fünf Spalten gegeben.

In [28]:
arr2d = arr[:20].reshape((4, 5))

Man kann auch in zwei (oder mehr) Dimensionen slicen. Beispiel:

```py
print(arr2d[:2, :2])
[['a' 'b']
 ['f' 'g']]
``` 
Benutzen Sie Slicing, um

a) die letzten drei Elemente der vorletzten Zeile auszugeben ("n", "o", "p")

In [30]:
arr2d[2, 2:]

array(['n', 'o', 'p'], dtype='<U1')

b) den Ausschnitt [["g", "h"], ["m", "n"]] zu bekommen

In [32]:
arr2d[1:3, 1:3]

array([['g', 'h'],
       ['m', 'n']], dtype='<U1')

#### Aufgabe (1)

Schreibe ein Python-Programm (**ohne NumPy**), welches folgende Temperaturen (Celsius) in Fahrenheit umrechnet!
```python
cel = [20.1, 20.8, 21.9, 22.5, 22.7, 21.8, 21.3, 20.9, 20.1]
```
$Fahrenheit =(Celsius \times \frac{9}{5})+32$

In [36]:
cel = [20.1, 20.8, 21.9, 22.5, 22.7, 21.8, 21.3, 20.9, 20.1]
print('Die Temperatur in Fahrenheit:')

for el in cel:
    f = (el * 9 / 5) + 32
    print(f' {f:.2f}')




Die Temperatur in Fahrenheit:
 68.18
 69.44
 71.42
 72.50
 72.86
 71.24
 70.34
 69.62
 68.18


#### Aufgabe (2)

Schreibe ein Python-Programm (**mit NumPy**), welches folgende Temperaturen (Celsius) in Fahrenheit umrechnet!
```python
cel = [20.1, 20.8, 21.9, 22.5, 22.7, 21.8, 21.3, 20.9, 20.1]
```

In [44]:
import numpy as np
print('Die Temperatur in Fahrenheit:')
cel =np.array([20.1, 20.8, 21.9, 22.5, 22.7, 21.8, 21.3, 20.9, 20.1])
f = cel * 9/5 + 32
print(f)




Die Temperatur in Fahrenheit:
[68.18 69.44 71.42 72.5  72.86 71.24 70.34 69.62 68.18]


#### Aufgabe (3):
Wie sieht die Ausgabe des folgenden Codes aus und warum?
```python
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])
```

In [53]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4] # b ist teil von a mit index von 1 bis 4, 4 nicht inklusiv : [2, 3, 4]
b[0] # ein Element von b mit index 0 ist 2
print(a[1]) # ein Element von a mit index 1 ist auch 2
print(f'{id(b[0]) == id(a[1])}') # und das Element hat gleiche id, was bedeutet, dass sie beide identisch sind

2
True


#### Aufgabe (4)

  
Schreibe zwei Python-Programme, welche jeweils eine Liste, und einen NumPy-Array aus hunderttausend ganzen Zahlen generieren. Diese Zahlen können gern durch Zufall generiert werden.

Dann ermitlle die Größe der Liste und die Größe des Arrays.  
Das ``sys``-Modul aus der Pythons Standardbibliothek verfügt über eine Funktion ``getsizeof``, um die Größe von Objekten zu berechnen.
Wir müssen die Größe der Datenstruktur (z.B. der Liste) und die Größe der enthaltenen Elemente addieren !

Zufallszahlen können mit Hilfe der Bibliothek `random` erzeugt werden, z.B. mit der Funktion `randomint(a,b)`. Diese erzeugt eine zufällige Ganzahl zwischen `a` und `b`.
Numpy hat eine eigene `random` Funktionen, hier kann `np.random.randint(a, b, size=anzahl)` benutzt werden.

In [106]:
import numpy as np
import random
import sys

liste = [random.randint(0, 100000) for _ in range(100000)]
print(f'Random Liste: \n {liste}\n')


arr = np.random.randint(1, 100000, 100000)
print(f'Random-Array: \n {arr}')


liste_groesse = sys.getsizeof(liste)
print(f' Die Größe von der Liste: {liste_groesse}')

el_groesse_liste = 0
for element in liste:
    el_groesse_liste += sys.getsizeof(element)

print(f' Summe der enthaltenen Elemente der Liste ist {el_groesse_liste}')
print(f'Summe Liste: {liste_groesse + el_groesse_liste}')

#array_groesse = arr.nbytes
array_groesse = sys.getsizeof(arr) # Was ist besser?
print(f'Die Größe von der Array: {array_groesse}')

el_groesse_arr= 0
for el in arr:
    el_groesse_arr += sys.getsizeof(el)
print(f'Summe der enthaltenen Elemente des Arrays ist {el_groesse_arr}')

print(f'Summe Array: {array_groesse + el_groesse_arr}')



Random Liste: 
 [11080, 52089, 77527, 2293, 84405, 76937, 10507, 93011, 42205, 19065, 14216, 1761, 27616, 29686, 31388, 39030, 17573, 22244, 8479, 35859, 37381, 11722, 2890, 90911, 38331, 47059, 98050, 14184, 22211, 8403, 21109, 11751, 20954, 56892, 24345, 42489, 27, 2409, 83501, 52995, 8496, 98281, 43011, 18025, 2687, 95716, 61607, 40400, 31959, 14810, 48117, 17650, 95964, 97262, 9485, 99937, 92603, 78846, 13036, 58634, 34773, 73025, 48028, 51419, 45742, 81792, 47557, 91510, 63137, 95978, 41684, 19383, 44644, 49278, 5557, 11495, 90130, 55874, 57523, 50512, 98619, 41787, 56410, 71335, 45521, 62864, 42659, 31412, 78047, 98331, 99693, 26864, 29945, 33542, 78131, 74096, 54341, 67664, 76946, 49665, 33783, 58093, 80335, 74564, 43419, 77807, 49358, 52881, 13492, 93576, 45686, 73517, 96880, 55701, 33535, 94458, 85306, 84412, 52821, 53066, 17058, 4993, 14, 41552, 81376, 93602, 55789, 6730, 62563, 13237, 73428, 62701, 37868, 19720, 30053, 28639, 57564, 2665, 7893, 77897, 62061, 44273, 46834, 18

#### Aufgabe (5)

Erweitere die Programme aus Aufgabe (4), sodass die Zeitdauer bei Erstellung von Liste und Array separat berechnet werden können.  
Das Modul ``time`` aus der Pythons Standardbibliothek verfügt über eine Funktion ``time``, welche den aktuellen Zeitpunkt als eine Kommazahl zurückliefert.  

Vergleiche dann die Zeitdauer von zwei Programmen.

In [5]:
import numpy as np
import random
import sys
import time 

start_time_list = time.time()

liste = [random.randint(0, 100000) for _ in range(100000)]
print(f'Random Liste: \n {liste}\n')

end_time_list = time.time()
time_fuer_listerstellung = end_time_list - start_time_list
print(f' Die Ersellung der Liste dauert: {time_fuer_listerstellung:.2f} Sekunden')



start_time_arr = time.time()
arr = np.random.randint(1, 100000, 100000)
print(f'Random-Array: \n {arr}')
end_time_arr = time.time()
time_fuer_erstellung_arr = end_time_arr - start_time_arr
print(f' Die Ersellung des Arrays dauert: {time_fuer_erstellung_arr:.2f}')


liste_groesse = sys.getsizeof(liste)
print(f' Die Größe von der Liste: {liste_groesse}')

el_groesse_liste = 0
for element in liste:
    el_groesse_liste += sys.getsizeof(element)

print(f' Summe der enthaltenen Elemente der Liste ist {el_groesse_liste} Sekunden')
print(f'Summe Liste: {liste_groesse + el_groesse_liste}')

#array_groesse = arr.nbytes
array_groesse = sys.getsizeof(arr) # Was ist besser?
print(f'Die Größe von der Array: {array_groesse}')

el_groesse_arr= 0
for el in arr:
    el_groesse_arr += sys.getsizeof(el)
print(f'Summe der enthaltenen Elemente des Arrays ist {el_groesse_arr}')

print(f'Summe Array: {array_groesse + el_groesse_arr}')

print(f' Die Erstellung der Liste dauert um {time_fuer_listerstellung -time_fuer_erstellung_arr:.2f} Sekunden länger')

Random Liste: 
 [67058, 82802, 39192, 68660, 24152, 14416, 77102, 29682, 78009, 36485, 62219, 69315, 46034, 13525, 79656, 68309, 67227, 40461, 16253, 45855, 34553, 59918, 48338, 50847, 86714, 69666, 20254, 58504, 75755, 21358, 79452, 14878, 83673, 17892, 27551, 13846, 93815, 74832, 16688, 73069, 92620, 29958, 41796, 12141, 7900, 39973, 29003, 91788, 21808, 37322, 66714, 39021, 24446, 16501, 90710, 50691, 24836, 61168, 22047, 93751, 25618, 69244, 96465, 32090, 46552, 31614, 55636, 86296, 63722, 83287, 93730, 51115, 38958, 6911, 91624, 2663, 1622, 51334, 65210, 38930, 50186, 50453, 85101, 83263, 55198, 58025, 59840, 73288, 72613, 58962, 42953, 9276, 48355, 32789, 30967, 61437, 49264, 83235, 43207, 16734, 98113, 80224, 35452, 97030, 99836, 85421, 2876, 64207, 39820, 44664, 87908, 18935, 66096, 42730, 78878, 83334, 82561, 35223, 92196, 24839, 61741, 63709, 24702, 34790, 16063, 94192, 50056, 94512, 56626, 87748, 95660, 83939, 40652, 57073, 69399, 67098, 82785, 48275, 24624, 24964, 33337, 67