# Numpy Teil 2

In [1]:
import numpy as np

### Zufallszahlen erzeugen

`seed()` 
setzt den Startwert des Zufallszahlengenerators.

In [12]:
np.random.seed(42)

`random()` zieht Zufallszahlen aus einer gleichverteilten Verteilung im Intervall [0, 1). Mit `size` kann die Anzahl der Werte angegeben werden oder die Dimension:

In [9]:
print(np.random.random())
print(np.random.random(size=5))
print(np.random.random(size=(3,3)))

0.3745401188473625
[0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
[[0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]]


`randint()`
zieht zufällige Ganzzahlen aus einem gegebenen Intervall

In [12]:
np.random.randint(1, 10, 5)  # 5 Ganzzahlen zwischen 1 und 10

array([9, 1, 9, 7, 9], dtype=int32)

In [13]:
np.random.randint(1, 100, size=(3,3)) # Mit ANgabe der Array Dimensionen

array([[88,  1,  8],
       [88, 63, 11],
       [81,  8, 35]], dtype=int32)

`choice()` zieht zufällig Werte aus einer gegebenen Liste oder Array.

In [22]:
np.random.choice([1, 2, 3, 4, 5, 6, 7, 8], size=3, replace=False) # 3 Werte aus der Liste, ohne Wiederholung wenn replace=False

array([8, 2, 4])

`permutation()` liefert eine zufällige Permutation einer Sequenz, ändert nicht das ursprüngliche Array sondern liefert den Wert als Rückgabe

In [22]:
arr = [1, 2, 3, 4]
arr_perm = np.random.permutation(arr)
print("Ausagangsarry:", arr)
arr_perm

Ausagangsarry: [1, 2, 3, 4]


array([1, 3, 2, 4])

`shuffle()`
vermischt eine Sequenz und ändert ursprüngliche Array verändert

In [27]:
arr = [1, 2, 3, 4]
np.random.shuffle(arr)
arr

[1, 2, 4, 3]

`uniform()`
zieht Stichproben aus einem Intervall

In [32]:
np.random.uniform(0, 100, 10)  # 10 Stichproben zwischen 0 und 1

array([94.29097039, 32.3202932 , 51.87906217, 70.30189589, 36.36296024,
       97.17820827, 96.24472949, 25.17822958, 49.72485059, 30.08783098])

`standard_normal()`
zieht Stichproben aus einer Normalverteilung mit dem Mittelwert 0 und der Standardabweichung 1<br>
alte Methode heisst `randn()`

In [33]:
np.random.standard_normal(10)  # 10 Stichproben

array([ 0.06023021,  2.46324211, -0.19236096,  0.30154734, -0.03471177,
       -1.16867804,  1.14282281,  0.75193303,  0.79103195, -0.90938745])

`normal()`
zieht Stichproben aus einer Normalverteilung (gausssche Verteilung)

In [35]:
np.random.normal(loc=0, scale=1, size=10)  # Mittelwert=0, Standardabweichung=1

array([-1.55066343,  0.06856297, -1.06230371,  0.47359243, -0.91942423,
        1.54993441, -0.78325329, -0.32206152,  0.81351722, -1.23086432])